//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Web.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leads
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public int DealerId { get; set; }
        public int ModelId { get; set; }
        public Nullable<int> AssignedUserId { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerContactNumber { get; set; }
        public int LeadStatusId { get; set; }
        public int LeadTypeId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string UserComments { get; set; }
    
        public virtual Dealers Dealers { get; set; }
        public virtual LeadStatus LeadStatus { get; set; }
        public virtual LeadType LeadType { get; set; }
        public virtual Models Models { get; set; }
        public virtual Services Services { get; set; }
        public virtual Users Users { get; set; }
    }
}
